name: vitessce-jupyter-examples
channels:
 - bioconda
 - conda-forge
dependencies:
 - python>=3.7
 - numpy>=1.14.0
 - pandas>=1.1.2
 - anndata>=0.7.4
 - scanpy>=1.6.0
 - jupyterlab>=1.0.10
 - zarr>=2.5.0
 - boto3>=1.16.30
 - pyBigWig>=0.3.17
 - leidenalg>=0.8.3
 - pip
 - pip:
   - loompy>=3.0.6
   - scikit-misc>=0.1.3
   - pybbi>=0.3.0